### ISSUE TITLE
EXC_BAD_ACCESS AFHTTPRequestSerializer XCTest with code for reproduction

### ISSUE THREAD

**Issue by r3b3l** [AFNetworking/AFNetworking#2523]
Initially I've raised attention for this problem through a comment on https://github.com/AFNetworking/AFNetworking/issues/2288 but I don't feel it gets the attention deserved that way, because the issue is already closed.

The problem is a crash under unit testing conditions with AFNetworking 2.4.0 and higher. It seems to occur when a second instance AFHTTPRequestSerializer is created. 

I've created a test project with minimal code for reproduction of the issue: https://github.com/r3b3l/AFNetworkingXCTestFail

**Comment by robmaceachern** [comment]
I'm also seeing this issue when running tests on device (iphone 6 - 8.1.2) and on the simulator (8.1).

**Comment by mattt** [comment]
Thanks for bringing this to my attention, @r3b3l. This is fixed by 0f3829f.

**Comment by mattt** [comment]
This change was causing a more substantial problem of causing these property changes to be ignored completely. As such, I reverted with df51854.

If anyone has any alternative suggestions, please let me know.

**Comment by mattt** [comment]
Fixed by 7d8e286. Re-reverting the implementation of `+automaticallyNotifiesObserversForKey:`, the solution was to manually implement will/did change methods to ensure KVO notification.

**Comment by robertmryan** [comment]
@mattt First, thanks for fixing the notifications for these keys.

Second, can you explain how turning off `automaticallyNotifiesObserversForKey`, but manually posting these notifications, solves this issue raised by r3b3l? Usually when you go through this process of turning off automatic notifications, it's usually because there are some situations in which the setter is called in which you don't want it to post the notification, but as you have the setter always post the notification anyway, it seems to defeat the purpose of turning off notifications. I presume there's some scenario where the notification is not getting posted by going through this process, but I'm not seeing it here. I'm just curious precisely what problem you're solving here.

Frankly, I never was able to reproduce the bug that he described, so it's hard for me to diagnose the problem, much less the solution. (I ran the test he provided with all of this `automaticallyNotifiesObserversForKey` and manual setters commented out without incident; I've used XCTest with AFNetworking in the past and never had the problem he described.)

Regardless, thanks for fixing the issue that this original mod introduced. We appreciate it.

**Comment by renguochao** [comment]
I still have a question, why KVO used in XCTest will crash? 
Could anyone explain it? Thanks in advance:)
