### ISSUE TITLE
[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] crash!

### ISSUE THREAD

**Issue by HellosunDong** [AFNetworking/AFNetworking#4564]
This problem has occurred before, I updated the afn version to the latest on April 29, 2020, and then published it to the App Store. I found that this problem still exists

AFNetworking | -[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] + 104
-- | --
1 AFNetworking | -[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] + 96
2 CFNetwork | _CFNetworkHTTPConnectionCacheSetLimit + 200344
3 Foundation | 0x00000001ad71b000 + 16099066846083406292
4 Foundation | 0x00000001ad71b000 + 1310855354820719784
5 Foundation | 0x00000001ad71b000 + 7808267036803595568
6 Foundation | 0x00000001ad71b000 + 1970088991730561316
7 Foundation | 0x00000001ad71b000 + 2036055291351664476
8 Foundation | 0x00000001ad71b000 + 12538634890088940060
9 libdispatch.dylib | 0x00000001ad10b000 + 8588967021767619484
10 libdispatch.dylib | 0x00000001ad10b000 + 3247726451008483288
11 libdispatch.dylib | 0x00000001ad10b000 + 6153389337057711960
12 libdispatch.dylib | 0x00000001ad10b000 + 12569597137525952184
13 libdispatch.dylib | 0x00000001ad10b000 + 11762994857633717204
14 libdispatch.dylib | 0x00000001ad10b000 + 16789925186186060676
15 libsystem_pthread.dylib | _pthread_wqthread + 6796739428992680152

AFNetworking version:4.0.1
Xcode version:11.3 (11C29)
Swift version: Now is using OC
Platform(s) running AFNetworking:iPhone X iPhone8p iPhone7p iPhone8 etc. iOS13+
macOS version running Xcode:10.15.3 (19D76)

**Comment by HellosunDong** [comment]
Hello, I still have this problem. The last reported crash was on May 21, 2020 18:25:20, the device type is iPhone7p system version iOS13.3

**Comment by Sesame123** [comment]
I have the same problem.And I have a lot of crash

**Comment by Sesame123** [comment]
#2102 SIGSEGV
SEGV_ACCERR

AFNetworking -[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:]

**Comment by jazuara** [comment]
I see this crash too.
The reason is 

`static NSError * ServerTrustError(SecTrustRef serverTrust, NSURL *url)
{
    NSBundle *CFNetworkBundle = [NSBundle bundleWithIdentifier:@"com.apple.CFNetwork"];
    NSString *defaultValue = @"The certificate for this server is invalid. You might be connecting to a server that is pretending to be “%@” which could put your confidential information at risk.";
    NSString *descriptionFormat = NSLocalizedStringWithDefaultValue(@"Err-1202.w", nil, CFNetworkBundle, defaultValue, @"") ?: defaultValue;
    NSString *localizedDescription = [descriptionFormat componentsSeparatedByString:@"%@"].count <= 2 ? [NSString localizedStringWithFormat:descriptionFormat, url.host] : descriptionFormat;
    NSDictionary *userInfo = @{
        NSURLErrorFailingURLErrorKey: url,
        NSURLErrorFailingURLStringErrorKey: url.absoluteString,
        NSURLErrorFailingURLPeerTrustErrorKey: (__bridge id)serverTrust,
        NSLocalizedDescriptionKey: localizedDescription
    };
    return [NSError errorWithDomain:NSURLErrorDomain code:NSURLErrorServerCertificateUntrusted userInfo:userInfo];
}`

serverTrust is nil which causes the crash trying to insert a nil value into the dictionary.

**Comment by jshier** [comment]
This was fixed in 4.0.1, please update.

**Comment by HellosunDong** [comment]
> This was fixed in 4.0.1, please update.
However, my current version is v4.0.1. This problem still exists, and the probability is relatively high, does the 4.0.1 version require any other configuration operations?

**Comment by SuperMarioBean** [comment]
Same here with AFNetworking 4.0.1

**Comment by jshier** [comment]
@jazuara That's the old function, you need to update, it was removed in 4.0.1.

@HellosunDong @SuperMarioBean Please post the (symbolicated) backtraces you're seeing for this crash.

**Comment by SuperMarioBean** [comment]
@jshier 
```
SIGSEGV

crashed thread:
1 Sephora 0x1000aa900-[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] (AFURLSessionManager.m:936)
2 CFNetwork 0x1838c037c__CFNetworkHTTPConnectionCacheSetLimit + 199996
3 Foundation 0x18084088c___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
4 Foundation 0x1807427cc-[NSBlockOperation main] + 104
5 Foundation 0x180842bcc___NSOPERATION_IS_INVOKING_MAIN__ + 24
6 Foundation 0x1807424a4-[NSOperation start] + 752
7 Foundation 0x1808435f8___NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
8 Foundation 0x1808430b8___NSOQSchedule_f + 184
9 libdispatch.dylib 0x180118db4__dispatch_block_async_invoke2 + 144
10 libdispatch.dylib 0x18010c33c__dispatch_client_callout + 20
11 libdispatch.dylib 0x18010eaf8__dispatch_continuation_pop + 408
12 libdispatch.dylib 0x18010e258__dispatch_async_redirect_invoke + 588
13 libdispatch.dylib 0x18011b5c0__dispatch_root_queue_drain + 348
14 libdispatch.dylib 0x18011bd9c__dispatch_worker_thread2 + 116
15 libsystem_pthread.dylib 0x1801736d8__pthread_wqthread + 216

main thread:
1 libsystem_kernel.dylib 0x180230784_mach_msg_trap + 8
2 CoreFoundation 0x1803e7080___CFRunLoopServiceMachPort + 152
3 CoreFoundation 0x1803e1e0c___CFRunLoopRun + 1156
4 CoreFoundation 0x1803e1660_CFRunLoopRunSpecific + 480
5 GraphicsServices 0x18a7f2604_GSEventRunModal + 164
6 UIKitCore 0x1845b615c_UIApplicationMain + 1944
7 Sephora 0x10000c8f8_main (main.m:26)
8 libdyld.dylib 0x18025d1ec_start + 4
```

**Comment by Sesame123** [comment]
too many crash,I used older version below 4.0，and update my APP

**Comment by walletsh** [comment]
Update to AFNetworking 4.0.1 and crash here.

**Comment by ElfSundae** [comment]
@SuperMarioBean Did you call `setSessionDidReceiveAuthenticationChallengeBlock`?

**Comment by SuperMarioBean** [comment]
> @SuperMarioBean Did you call `setSessionDidReceiveAuthenticationChallengeBlock`?

No, I didn't call this method

**Comment by iosyong** [comment]
[[AFNetworking 4.0.1]]
崩溃线程
AFNetworking    0x1f62c    -[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:]
CFNetwork    0x1838be09c    __CFNetworkHTTPConnectionCacheSetLimit + 199996
Foundation    0x18083fcfc    ___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
Foundation    0x180741c3c    -[NSBlockOperation main] + 104
Foundation    0x18084203c    ___NSOPERATION_IS_INVOKING_MAIN__ + 24
Foundation    0x180741914    -[NSOperation start] + 752
Foundation    0x180842a68    ___NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
Foundation    0x180842528    ___NSOQSchedule_f + 184
libdispatch.dylib    0x180118db4    __dispatch_block_async_invoke2 + 144
libdispatch.dylib    0x18010c33c    __dispatch_client_callout + 20
libdispatch.dylib    0x18010eaf8    __dispatch_continuation_pop + 408
libdispatch.dylib    0x18010e258    __dispatch_async_redirect_invoke + 588
libdispatch.dylib    0x18011b5c0    __dispatch_root_queue_drain + 348
libdispatch.dylib    0x18011bd9c    __dispatch_worker_thread2 + 116
libsystem_pthread.dylib    0x1801736d8    __pthread_wqthread + 216

binaryImages:

ZhenPinWang    2D794353-1C87-3148-8E3E-11B79C93DF4B    arm64    1
AFNetworking    A52A4FA9-E5F7-381A-875D-2F3659E40E01    arm64    2
CFNetwork    EE91F2C9-2464-3965-8AAB-4A986EBE9F72    arm64e    0
Foundation    19FAB59F-6527-3245-85BB-905FD4255CDE    arm64e    0
libdispatch.dylib    CAFEEE86-4C94-3AC9-8853-BFE11F70C0F4    arm64e    0
libsystem_pthread.dylib    4CF76CD7-DC5B-37CF-83D7-46153D0D3962    arm64e    0
libsystem_kernel.dylib    42BDCD41-02A6-3529-A271-0E6402154A44    arm64e    0
CoreFoundation    AF42303F-57B6-3C11-8F18-8E80ABF7D886    arm64e    0
GraphicsServices    FDD62141-EAD1-3C35-9F51-9D1F1343F394    arm64e    0
UIKitCore    32D99ABD-E47B-38D8-BBD1-68AEA293A9A6    arm64e    0
libdyld.dylib    E5E56A85-E4D6-332E-9F32-FED4B986AFE0    arm64e    0

主线程
libsystem_kernel.dylib    0x180230784    _mach_msg_trap + 8
CoreFoundation    0x1803e7314    ___CFRunLoopServiceMachPort + 152
CoreFoundation    0x1803e20a0    ___CFRunLoopRun + 1156
CoreFoundation    0x1803e18f4    _CFRunLoopRunSpecific + 480
GraphicsServices    0x18a7f8604    _GSEventRunModal + 164
UIKitCore    0x1845b5358    _UIApplicationMain + 1944
ZhenPinWang    0x1004bae48    _main (main.m:0)
libdyld.dylib    0x18025d2dc    _start + 4

binaryImages:

ZhenPinWang    2D794353-1C87-3148-8E3E-11B79C93DF4B    arm64    1
AFNetworking    A52A4FA9-E5F7-381A-875D-2F3659E40E01    arm64    2
CFNetwork    EE91F2C9-2464-3965-8AAB-4A986EBE9F72    arm64e    0
Foundation    19FAB59F-6527-3245-85BB-905FD4255CDE    arm64e    0
libdispatch.dylib    CAFEEE86-4C94-3AC9-8853-BFE11F70C0F4    arm64e    0
libsystem_pthread.dylib    4CF76CD7-DC5B-37CF-83D7-46153D0D3962    arm64e    0
libsystem_kernel.dylib    42BDCD41-02A6-3529-A271-0E6402154A44    arm64e    0
CoreFoundation    AF42303F-57B6-3C11-8F18-8E80ABF7D886    arm64e    0
GraphicsServices    FDD62141-EAD1-3C35-9F51-9D1F1343F394    arm64e    0
UIKitCore    32D99ABD-E47B-38D8-BBD1-68AEA293A9A6    arm64e    0
libdyld.dylib    E5E56A85-E4D6-332E-9F32-FED4B986AFE0    arm64e    0

**Comment by wizardch** [comment]
Have the same problem on version 4.0.1

**Comment by programYZ** [comment]
Have the same problem on version 4.0.0

**Comment by dhawanheena26** [comment]
Have the same crash problem in version 4.0.1, it occurs at [self af_resume] in my case; in AFURLSessionManager, its random. 
AFNetworking version:4.0.1
Xcode version:11.3 (11C29)
Swift version: Using Objective C

**Comment by wizardch** [comment]
Offical consider to solve the problem?

**Comment by King-Eternal** [comment]
Hello, I still have this problem.

**Comment by 1oo1** [comment]
Same here in 4.0.1.

```
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000010
VM Region Info: 0x10 is not in any region.  Bytes before following region: 4334845936
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                 0000000102608000-00000001028cc000 [ 2832K] r-x/r-x SM=COW  ...ip.app/XXX

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [36645]
Triggered by Thread:  19

Thread 19 Crashed:
0   AFNetworking                  	0x0000000103c499c8 -[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] + 104 (AFURLSessionManager.m:936)
1   AFNetworking                  	0x0000000103c499c0 -[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] + 96 (AFURLSessionManager.m:936)
2   CFNetwork                     	0x00000001af2a209c __63-[NSURLSession delegate_didReceiveChallenge:completionHandler:]_block_invoke + 148 (Session.mm:449)
3   Foundation                    	0x00000001ac223cfc __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24 (NSOperation.m:1541)
4   Foundation                    	0x00000001ac125c3c -[NSBlockOperation main] + 104 (NSOperation.m:1560)
5   Foundation                    	0x00000001ac22603c __NSOPERATION_IS_INVOKING_MAIN__ + 24 (NSOperation.m:2184)
6   Foundation                    	0x00000001ac125914 -[NSOperation start] + 752 (NSOperation.m:2201)
7   Foundation                    	0x00000001ac226a68 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24 (NSOperation.m:2215)
8   Foundation                    	0x00000001ac226528 __NSOQSchedule_f + 184 (NSOperation.m:2226)
9   libdispatch.dylib             	0x00000001abafcdb4 _dispatch_block_async_invoke2 + 144 (queue.c:525)
10  libdispatch.dylib             	0x00000001abaf033c _dispatch_client_callout + 20 (object.m:495)
11  libdispatch.dylib             	0x00000001abaf2af8 _dispatch_continuation_pop + 408 (inline_internal.h:2484)
12  libdispatch.dylib             	0x00000001abaf2258 _dispatch_async_redirect_invoke + 588 (queue.c:803)
13  libdispatch.dylib             	0x00000001abaff5c0 _dispatch_root_queue_drain + 348 (inline_internal.h:2525)
14  libdispatch.dylib             	0x00000001abaffd9c _dispatch_worker_thread2 + 116 (queue.c:6628)
15  libsystem_pthread.dylib       	0x00000001abb576d8 _pthread_wqthread + 216 (pthread.c:2364)
16  libsystem_pthread.dylib       	0x00000001abb5d9c8 start_wqthread + 8

```

**Comment by ElfSundae** [comment]
@1oo1 Did you call `setSessionDidReceiveAuthenticationChallengeBlock:`?

**Comment by 1oo1** [comment]
@ElfSundae No, and that's why I was confused after investigated.

**Comment by ElfSundae** [comment]
@1oo1 Can not reproduce?

**Comment by 1oo1** [comment]
@ElfSundae YES, just received crash reports.

**Comment by wxiaowu** [comment]
The same problem here with iOS13+. Works fine on iOS12.

**Comment by wizardch** [comment]
The crash problem  occurs too many times on iOS13+.

**Comment by iosyong** [comment]
I need superman to help me, thank you.

**Comment by lgc107** [comment]
> @1oo1 Did you call `setSessionDidReceiveAuthenticationChallengeBlock:`?

respondsToSelector:` implementation forces `URLSession:didReceiveChallenge:completionHandler:` to be called only if `self.sessionDidReceiveAuthenticationChallenge` is not nil

but I didn't call  `setSessionDidReceiveAuthenticationChallengeBlock:`

**Comment by ACommonChinese** [comment]
Me too, not call setSessionDidReceiveAuthenticationChallengeBlock, but crash many times,  0x10001fb78    -[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] +104 (AFURLSessionManager.m:936)
CFNetwork    0x1838957b0    _CFNetworkHTTPConnectionCacheSetLimit (missing_symbol)
Foundation    0x18086e3f0    oq_synthesize_backing_queue +352
Foundation    0x180779710    -[NSString(NSPathUtilities) stringByDeletingPathExtension] +296
Foundation    0x18087064c    _NSAbbreviatePathWithTilde +268
Foundation    0x180779414    -[NSClassicMapTable setItem:forKnownAbsentKey:] +180
Foundation    0x180871044    _NSStandardizePathUsingCache +532
Foundation    0x180870b10    _NSResolveSymlinksInPathUsingCache +416
libdispatch.dylib    0x180142dd0    _dispatch_non_barrier_waiter_redirect_or_wake +236
libdispatch.dylib    0x18015f524    ___dispatch_transform_to_base32_with_table_block_invoke +56
libdispatch.dylib    0x180139274    dispatch_barrier_async$VARIANT$armv81 +136
libdispatch.dylib    0x1801389e8    _dispatch_block_sync_invoke$VARIANT$armv81 +236
libdispatch.dylib    0x180145534    _dispatch_kevent_worker_thread +2072
libdispatch.dylib    0x180145cd0    _dispatch_workloop_worker_thread +1732
libsystem_pthread.dylib    0x1801b0b38    pthread_mutexattr_gettype +16

...

**Comment by xuwenxindeai** [comment]
0 ArtVideoWBTeacher | -[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] (AFURLSessionManager.m:936)
-- | --
1 ArtVideoWBTeacher | -[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] (AFURLSessionManager.m:936)
2 CFNetwork | _CFNetworkHTTPConnectionCacheSetLimit + 208192
3 Foundation | ___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
4 Foundation | -[NSBlockOperation main] + 84
5 Foundation | ___NSOPERATION_IS_INVOKING_MAIN__ + 20
6 Foundation | -[NSOperation start] + 740
7 Foundation | ___NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 20
8 Foundation | ___NSOQSchedule_f + 180
9 libdispatch.dylib | __dispatch_block_async_invoke2 + 104
10 libdispatch.dylib | __dispatch_client_callout + 16
11 libdispatch.dylib | __dispatch_continuation_pop$VARIANT$mp + 412
12 libdispatch.dylib | __dispatch_async_redirect_invoke + 656
13 libdispatch.dylib | __dispatch_root_queue_drain + 376
14 libdispatch.dylib | __dispatch_worker_thread2 + 124
15 libsystem_pthread.dylib | _pthread_wqthread + 212

**Comment by RayFor24** [comment]
I have the same problem.And I have a lot of crash .
 AFNetworking version:4.0.1  
Platform(s) running AFNetworking:iPhone 12proMax  iPhone 12pro iPhone 12 iPhone X iPhone8p iPhone7p iPhone8 etc. iOS13+

0x101984d14-[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] (AFURLSessionManager.m:936)
2CFNetwork0x180c2d898__CFNetworkHTTPConnectionCacheSetLimit + 150096
3Foundation0x1817a4850___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
4Foundation0x181691740-[NSBlockOperation main] + 104
5Foundation0x1817a6ca4___NSOPERATION_IS_INVOKING_MAIN__ + 24
6Foundation0x1816913c8-[NSOperation start] + 808
7Foundation0x1817a774c___NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
8Foundation0x1817a71d4___NSOQSchedule_f + 184
9libdispatch.dylib0x180057fb8__dispatch_block_async_invoke2 + 148
10libdispatch.dylib0x180049db0__dispatch_client_callout + 20
11libdispatch.dylib0x18004d12c__dispatch_continuation_pop + 416
12libdispatch.dylib0x18004c854__dispatch_async_redirect_invoke + 592
13libdispatch.dylib0x18005a93c__dispatch_root_queue_drain + 356
14libdispatch.dylib0x18005b120__dispatch_worker_thread2 + 116
15libsystem_pthread.dylib0x1cbc277c8__pthread_wqthread + 216

**Comment by jasenhuang** [comment]
it should be a bug of NSURLSession

**Comment by xuwenxindeai** [comment]
大佬们解决了吗

**Comment by Sesame123** [comment]
没敢回退，用的老版本



发自我的iPhone


------------------ Original ------------------
From: xuwenxindeai ***@***.***&gt;
Date: Thu,Apr 22,2021 0:07 PM
To: AFNetworking/AFNetworking ***@***.***&gt;
Cc: Sesame123 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [AFNetworking/AFNetworking] [AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] crash! (#4564)





 
大佬们解决了吗

**Comment by xuwenxindeai** [comment]
> 没敢回退，用的老版本发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: xuwenxindeai ***@***.***&gt; Date: Thu,Apr 22,2021 0:07 PM To: AFNetworking/AFNetworking ***@***.***&gt; Cc: Sesame123 ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [AFNetworking/AFNetworking] [AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] crash! (#4564) 大佬们解决了吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
老版本没问题？

**Comment by gxhx** [comment]
anybody fixed it？

**Comment by LiJinShi** [comment]
This bug should not be related to AFN. When we use singleton encapsulation, we should lock requestSerializer and responseSerializer instead of lazy loading.
```objectivec
- (AFJSONResponseSerializer *)afJSONResponseSerializer {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _afJSONResponseSerializer = [AFJSONResponseSerializer serializer];
    });
    return _afJSONResponseSerializer;
}

- (AFJSONRequestSerializer *)afJSONRequestSerializer {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _afJSONRequestSerializer = [AFJSONRequestSerializer serializer];
    });
    return _afJSONRequestSerializer;
}
```
When I changed it to the above method, my app no longer had the same Bug。

**Comment by leung-c** [comment]
I have the same crash before, but rarely. recently it appeared a lot, mostly on iOS15 devices. here is backtraces:

1 | XXXX| -[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] (in XXXX) (AFURLSessionManager.m:936)
-- | -- | --
2 | XXXX | -[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] (in XXXX) (AFURLSessionManager.m:936)
3 | CFNetwork | 0x0000000180b48088 (in CFNetwork) + 164
4 | Foundation | __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ (in Foundation) + 24
5 | Foundation | -[NSBlockOperation main] (in Foundation) + 104
6 | Foundation | __NSOPERATION_IS_INVOKING_MAIN__ (in Foundation) + 24
7 | Foundation | -[NSOperation start] (in Foundation) + 804
8 | Foundation | __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ (in Foundation) + 24
9 | Foundation | __NSOQSchedule_f (in Foundation) + 184
10 | libdispatch.dylib | _dispatch_block_async_invoke2 (in libdispatch.dylib) + 148
11 | libdispatch.dylib | _dispatch_client_callout (in libdispatch.dylib) + 20
12 | libdispatch.dylib | _dispatch_continuation_pop (in libdispatch.dylib) + 524
13 | libdispatch.dylib | _dispatch_async_redirect_invoke (in libdispatch.dylib) + 712
14 | libdispatch.dylib | _dispatch_root_queue_drain (in libdispatch.dylib) + 416
15 | libdispatch.dylib | _dispatch_worker_thread2 (in libdispatch.dylib) + 172
16 | libsystem_pthread.dylib | _pthread_wqthread (in libsystem_pthread.dylib) + 228

**Comment by haiwei-Lee** [comment]
me too !
    0x101a2d354-[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] (AFURLSessionManager.m:936)
2 CFNetwork0x1838957b0__CFNetworkHTTPConnectionCacheSetLimit + 212288
3 Foundation0x18086e3f0_oq_synthesize_backing_queue + 356
4 Foundation0x180779710-[NSString(NSPathUtilities) stringByDeletingPathExtension] + 300
5 Foundation0x18087064c__NSAbbreviatePathWithTilde + 272
6 Foundation0x180779414-[NSClassicMapTable setItem:forKnownAbsentKey:] + 184
7 Foundation0x180871044__NSStandardizePathUsingCache + 536
8 Foundation0x180870b10__NSResolveSymlinksInPathUsingCache + 420
9 libdispatch.dylib0x180111c8c__dispatch_non_barrier_waiter_redirect_or_wake + 252
10 libdispatch.dylib0x18015f524____dispatch_transform_to_base32_with_table_block_invoke + 60
11 libdispatch.dylib0x180107e98_dispatch_barrier_async$VARIANT$mp + 0
12 libdispatch.dylib0x1801075ec__dispatch_block_sync_invoke$VARIANT$mp + 184
13 libdispatch.dylib0x180114438__dispatch_kevent_worker_thread + 2040
14 libdispatch.dylib0x180114bf8__dispatch_workloop_worker_thread + 1720
15 libsystem_pthread.dylib0x1801b0b38_pthread_mutexattr_gettype + 20

**Comment by haiwei-Lee** [comment]
me too , crash information:

AFNetworking version:4.0.1

Device： | iPhone 7 Plus | 

  0x101a2d354-[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] (AFURLSessionManager.m:936)
2 CFNetwork0x1838957b0__CFNetworkHTTPConnectionCacheSetLimit + 212288
3 Foundation0x18086e3f0_oq_synthesize_backing_queue + 356
4 Foundation0x180779710-[NSString(NSPathUtilities) stringByDeletingPathExtension] + 300
5 Foundation0x18087064c__NSAbbreviatePathWithTilde + 272
6 Foundation0x180779414-[NSClassicMapTable setItem:forKnownAbsentKey:] + 184
7 Foundation0x180871044__NSStandardizePathUsingCache + 536
8 Foundation0x180870b10__NSResolveSymlinksInPathUsingCache + 420
9 libdispatch.dylib0x180111c8c__dispatch_non_barrier_waiter_redirect_or_wake + 252
10 libdispatch.dylib0x18015f524____dispatch_transform_to_base32_with_table_block_invoke + 60
11 libdispatch.dylib0x180107e98_dispatch_barrier_async$VARIANT$mp + 0
12 libdispatch.dylib0x1801075ec__dispatch_block_sync_invoke$VARIANT$mp + 184
13 libdispatch.dylib0x180114438__dispatch_kevent_worker_thread + 2040
14 libdispatch.dylib0x180114bf8__dispatch_workloop_worker_thread + 1720
15 libsystem_pthread.dylib0x1801b0b38_pthread_mutexattr_gettype + 20

**Comment by leung-c** [comment]
> I have the same crash before, but rarely. recently it appeared a lot, mostly on iOS15 devices. here is backtraces:
> 
> 1	XXXX	-[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] (in XXXX) (AFURLSessionManager.m:936)
> 2	XXXX	-[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] (in XXXX) (AFURLSessionManager.m:936)
> 3	CFNetwork	0x0000000180b48088 (in CFNetwork) + 164
> 4	Foundation	**NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK** (in Foundation) + 24
> 5	Foundation	-[NSBlockOperation main] (in Foundation) + 104
> 6	Foundation	**NSOPERATION_IS_INVOKING_MAIN** (in Foundation) + 24
> 7	Foundation	-[NSOperation start] (in Foundation) + 804
> 8	Foundation	**NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION** (in Foundation) + 24
> 9	Foundation	__NSOQSchedule_f (in Foundation) + 184
> 10	libdispatch.dylib	_dispatch_block_async_invoke2 (in libdispatch.dylib) + 148
> 11	libdispatch.dylib	_dispatch_client_callout (in libdispatch.dylib) + 20
> 12	libdispatch.dylib	_dispatch_continuation_pop (in libdispatch.dylib) + 524
> 13	libdispatch.dylib	_dispatch_async_redirect_invoke (in libdispatch.dylib) + 712
> 14	libdispatch.dylib	_dispatch_root_queue_drain (in libdispatch.dylib) + 416
> 15	libdispatch.dylib	_dispatch_worker_thread2 (in libdispatch.dylib) + 172
> 16	libsystem_pthread.dylib	_pthread_wqthread (in libsystem_pthread.dylib) + 228

I have solved this problem, details see: https://github.com/AFNetworking/AFNetworking/issues/4687 
Maybe you can find out whether sessionDidReceiveAuthenticationChallenge is set to nil under some condition, and if it happens to require SSL authentication, the system calls the relevant delegate method, which will hit the assertion and crash

**Comment by pangia** [comment]
@leung-c What was your workaround?

**Comment by iosyong** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
